"""Initial migration

Revision ID: 6c37f5677a87
Revises: 
Create Date: 2025-05-07 12:14:35.022280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c37f5677a87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('new', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
